# Generated by Django 5.2.3 on 2025-06-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_favorites_readbooks_wanttoread_delete_booklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='ReadBooks',
        ),
        migrations.DeleteModel(
            name='WantToRead',
        ),
    ]
